# CoroutineTests examples

add_executable(simplegenerator simplegenerator.cpp)
target_link_libraries(simplegenerator PRIVATE CoroutineTests)
add_executable(generator generator.cpp)
target_link_libraries(generator PRIVATE CoroutineTests)
add_executable(lazy lazy.cpp)
target_link_libraries(lazy PRIVATE CoroutineTests)
add_executable(task task.cpp)
target_link_libraries(task PRIVATE CoroutineTests)
add_executable(datasource datasource.cpp)
target_link_libraries(datasource PRIVATE CoroutineTests)
add_executable(datasink datasink.cpp)
target_link_libraries(datasink PRIVATE CoroutineTests)
add_executable(nestabletask nestabletask.cpp)
target_link_libraries(nestabletask PRIVATE CoroutineTests)
add_executable(event event.cpp)
target_link_libraries(event PRIVATE CoroutineTests)
add_executable(async async.cpp)
target_link_libraries(async PRIVATE CoroutineTests)
add_executable(pingpong pingpong.cpp)
target_link_libraries(pingpong PRIVATE CoroutineTests)
add_executable(gaudi gaudi.cpp)

add_executable(alien alien.cpp)
target_link_libraries(alien PRIVATE CoroutineTests)
add_executable(alien_manual alien_manual.cpp)
target_link_libraries(alien_manual PRIVATE CoroutineTests)
add_executable(alien_manual_semaphore alien_manual_semaphore.cpp)
target_link_libraries(alien_manual_semaphore PRIVATE CoroutineTests)
add_executable(when_all when_all.cpp)
target_link_libraries(when_all PRIVATE CoroutineTests)


if(BUILD_STDEXEC)
  add_executable(task_stdexec task_exec.cpp)
  target_link_libraries(task_stdexec PRIVATE CoroutineTests STDEXEC::stdexec)
  if (BUILD_TBB)
    add_executable(tbb_stdexec tbb_scheduler.cpp)
    target_link_libraries(tbb_stdexec PRIVATE CoroutineTests STDEXEC::stdexec TBB::tbb)
  endif()
endif()

if(BUILD_BEMAN_TASK)
  add_executable(task_beman task_exec.cpp)
  target_link_libraries(task_beman PRIVATE CoroutineTests beman::task)
  target_compile_definitions(task_beman PUBLIC "USE_BEMAN")
  if (BUILD_TBB)
    add_executable(tbb_beman tbb_scheduler.cpp)
    target_link_libraries(tbb_beman PRIVATE CoroutineTests beman::task TBB::tbb)
    target_compile_definitions(tbb_beman PUBLIC "USE_BEMAN")
  endif()
endif()
