# CoroutineTests examples

add_executable(simplegenerator simplegenerator.cpp)
target_link_libraries(simplegenerator PRIVATE CoroutineTests)
add_executable(generator generator.cpp)
target_link_libraries(generator PRIVATE CoroutineTests)
add_executable(lazy lazy.cpp)
target_link_libraries(lazy PRIVATE CoroutineTests)
add_executable(task task.cpp)
target_link_libraries(task PRIVATE CoroutineTests)
add_executable(datasource datasource.cpp)
target_link_libraries(datasource PRIVATE CoroutineTests)
add_executable(datasink datasink.cpp)
target_link_libraries(datasink PRIVATE CoroutineTests)
add_executable(nestabletask nestabletask.cpp)
target_link_libraries(nestabletask PRIVATE CoroutineTests)
add_executable(event event.cpp)
target_link_libraries(event PRIVATE CoroutineTests)
add_executable(async async.cpp)
target_link_libraries(async PRIVATE CoroutineTests)
add_executable(pingpong pingpong.cpp)
target_link_libraries(pingpong PRIVATE CoroutineTests)
add_executable(gaudi gaudi.cpp)

add_executable(alien alien.cpp)
target_link_libraries(alien PRIVATE CoroutineTests)
add_executable(alien_manual alien_manual.cpp)
target_link_libraries(alien_manual PRIVATE CoroutineTests)
add_executable(alien_manual_semaphore alien_manual_semaphore.cpp)
target_link_libraries(alien_manual_semaphore PRIVATE CoroutineTests)
add_executable(alien_when_all alien_when_all.cpp)
target_link_libraries(alien_when_all PRIVATE CoroutineTests)
add_executable(alien_sync_wait alien_sync_wait.cpp)
target_link_libraries(alien_sync_wait PRIVATE CoroutineTests)
add_executable(alien_counting_scope alien_counting_scope.cpp)
target_link_libraries(alien_counting_scope PRIVATE CoroutineTests)
add_executable(alien_schedule_on alien_schedule_on.cpp)
target_link_libraries(alien_schedule_on PRIVATE CoroutineTests)
add_executable(alien_this_task alien_this_task.cpp)
target_link_libraries(alien_this_task PRIVATE CoroutineTests)

if(BUILD_STDEXEC)
  add_executable(exec_task_stdexec exec_task.cpp)
  target_link_libraries(exec_task_stdexec PRIVATE CoroutineTests STDEXEC::stdexec)
  if (BUILD_TBB)
    add_executable(exec_tbb_stdexec exec_tbb.cpp)
    target_link_libraries(exec_tbb_stdexec PRIVATE CoroutineTests STDEXEC::stdexec TBB::tbb)
    add_executable(exec_reschedule_stdexec exec_reschedule.cpp)
    target_link_libraries(exec_reschedule_stdexec PRIVATE CoroutineTests STDEXEC::stdexec TBB::tbb)
  endif()
endif()

if(BUILD_BEMAN_TASK)
  add_executable(exec_task_beman exec_task.cpp)
  target_link_libraries(exec_task_beman PRIVATE CoroutineTests beman::execution)
  target_compile_definitions(exec_task_beman PUBLIC "USE_BEMAN")
  if (BUILD_TBB)
    add_executable(exec_tbb_beman exec_tbb.cpp)
    target_link_libraries(exec_tbb_beman PRIVATE CoroutineTests beman::execution TBB::tbb)
    target_compile_definitions(exec_tbb_beman PUBLIC "USE_BEMAN")
    add_executable(exec_reschedule_beman exec_reschedule.cpp)
    target_link_libraries(exec_reschedule_beman PRIVATE CoroutineTests beman::execution TBB::tbb)
    target_compile_definitions(exec_reschedule_beman PUBLIC "USE_BEMAN")
  endif()
endif()


if(BUILD_CAPY)
  add_executable(capy_task capy_task.cpp)
  target_link_libraries(capy_task PRIVATE CoroutineTests Boost::capy)
  if (BUILD_TBB)
    add_executable(capy_tbb capy_tbb.cpp)
    target_link_libraries(capy_tbb PRIVATE CoroutineTests Boost::capy TBB::tbb)
  endif()
endif()

if(BUILD_CUDA AND BUILD_TBB)
  add_library(nanospin nanospin.cu)
  add_executable(alien_reco alien_reco.cpp)
  target_link_libraries(alien_reco PRIVATE CoroutineTests CUDA::cudart CUDA::nvtx3 TBB::tbb nanospin)
  add_executable(alien_delegate alien_delegate.cpp)
  target_link_libraries(alien_delegate PRIVATE CoroutineTests CUDA::cudart CUDA::nvtx3 TBB::tbb nanospin)
  add_executable(alien_event_poll alien_event_poll.cpp)
  target_link_libraries(alien_event_poll PRIVATE CoroutineTests CUDA::cudart CUDA::nvtx3 TBB::tbb nanospin)
  if(BUILD_STDEXEC)
    add_executable(exec_reco_stdexec exec_reco.cpp)
    target_link_libraries(exec_reco_stdexec PRIVATE CoroutineTests CUDA::cudart CUDA::nvtx3  TBB::tbb STDEXEC::stdexec nanospin)
    add_executable(exec_delegate_stdexec exec_delegate.cpp)
    target_link_libraries(exec_delegate_stdexec PRIVATE CoroutineTests CUDA::cudart CUDA::nvtx3 TBB::tbb STDEXEC::stdexec nanospin)
    add_executable(exec_event_poll_stdexec exec_event_poll.cpp)
    target_link_libraries(exec_event_poll_stdexec PRIVATE CoroutineTests CUDA::cudart CUDA::nvtx3 TBB::tbb STDEXEC::stdexec nanospin)
  endif()
  if(BUILD_BEMAN_TASK)
    add_executable(exec_reco_beman exec_reco.cpp)
    target_link_libraries(exec_reco_beman PRIVATE CoroutineTests CUDA::cudart CUDA::nvtx3 TBB::tbb beman::execution nanospin)
    target_compile_definitions(exec_reco_beman PUBLIC "USE_BEMAN")
    add_executable(exec_delegate_beman exec_delegate.cpp)
    target_link_libraries(exec_delegate_beman PRIVATE CoroutineTests CUDA::cudart CUDA::nvtx3 TBB::tbb beman::execution nanospin)
    target_compile_definitions(exec_delegate_beman PUBLIC "USE_BEMAN")
  #  add_executable(exec_event_poll_beman exec_event_poll.cpp)
  #  target_link_libraries(exec_event_poll_beman PRIVATE CoroutineTests CUDA::cudart TBB::tbb beman::execution nanospin)
  #  target_compile_definitions(exec_event_poll_beman PUBLIC "USE_BEMAN")
  endif()
  if(BUILD_CAPY)
    add_executable(capy_reco capy_reco.cpp)
    target_link_libraries(capy_reco PRIVATE CoroutineTests CUDA::cudart CUDA::nvtx3 TBB::tbb Boost::capy nanospin)
    add_executable(capy_delegate capy_delegate.cpp)
    target_link_libraries(capy_delegate PRIVATE CoroutineTests CUDA::cudart CUDA::nvtx3 TBB::tbb Boost::capy nanospin)
    add_executable(capy_event_poll capy_event_poll.cpp)
    target_link_libraries(capy_event_poll PRIVATE CoroutineTests CUDA::cudart CUDA::nvtx3 TBB::tbb Boost::capy nanospin)
  endif()
endif()
